// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: pairs.sql

package db

import (
	"context"
	"database/sql"
)

const createPair = `-- name: CreatePair :one
INSERT INTO pairs (start_date)
VALUES ($1)
RETURNING id, create_time, update_time, start_date
`

func (q *Queries) CreatePair(ctx context.Context, startDate sql.NullTime) (Pair, error) {
	row := q.db.QueryRowContext(ctx, createPair, startDate)
	var i Pair
	err := row.Scan(
		&i.ID,
		&i.CreateTime,
		&i.UpdateTime,
		&i.StartDate,
	)
	return i, err
}
