// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreatePair(ctx context.Context, startDate sql.NullTime) (Pair, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUsersPair(ctx context.Context, arg CreateUsersPairParams) (UserPair, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	GetBlog(ctx context.Context, id uuid.UUID) (Blog, error)
	GetInvitation(ctx context.Context, id int64) (Invitation, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateInvitation(ctx context.Context, arg UpdateInvitationParams) (Invitation, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
