// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: user_pairs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUsersPair = `-- name: CreateUsersPair :one
INSERT INTO user_pairs (pair_id, user_id)
VALUES ($1, $2)
RETURNING pair_id, user_id
`

type CreateUsersPairParams struct {
	PairID int64     `json:"pair_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateUsersPair(ctx context.Context, arg CreateUsersPairParams) (UserPair, error) {
	row := q.db.QueryRowContext(ctx, createUsersPair, arg.PairID, arg.UserID)
	var i UserPair
	err := row.Scan(&i.PairID, &i.UserID)
	return i, err
}
